services:
  db:
    image: postgres:16-alpine
    restart: always
    container_name: postgresql
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: ecommerce-api
    environment:
      DATABASE_URL: postgres://${DB_USERNAME}:${DB_PASSWORD}@db:5432/ecommerce
    ports:
      - 3000:3000
    depends_on:
      - db

volumes:
  pgdata: